// Generated by CoffeeScript 1.8.0
module.exports = function() {
  this.initHelpers = function() {
    var harvester, spawnHelpers;
    harvester = require('harvester');
    spawnHelpers = require('spawn_helpers');
    return spawnHelpers().initProrotypeHelpers();
  };
  this.initConsoleHelpers = function() {
    var console_helper;
    console_helper = require('helper');
    return console_helper(Game);
  };
  this.initMainLoop = function() {};
  return this;
};
