// Generated by CoffeeScript 1.8.0
module.exports = function() {
  this.initHelpers = function() {
    var spawnHelpers;
    this.harvester = require('harvester');
    spawnHelpers = require('spawn_helpers');
    return spawnHelpers().initPrototypeHelpers();
  };
  this.initConsoleHelper = function() {
    var console_helper;
    console_helper = require('helper');
    return console_helper(Game);
  };
  this.initMainLoop = function() {
    var creep, name, targets, _results;
    _results = [];
    for (name in Game.creeps) {
      creep = Game.creeps[name];
      if (creep.memory.role === 'harvester') {
        this.harvester(creep);
      }
      if (creep.memory.role === 'builder') {
        if (creep.carry.energy === 0) {
          creep.moveTo(Game.spawns.Spawn1);
          Game.spawns.Spawn1.transferEnergy(creep);
        } else {
          targets = creep.room.find(global.FIND_CONSTRUCTION_SITES);
          if (targets.length) {
            creep.moveTo(targets[0]);
            creep.build(targets[0]);
          }
        }
      }
      if (creep.memory.role === 'guard') {
        targets = creep.room.find(global.FIND_HOSTILE_CREEPS);
        if (targets.length) {
          creep.moveTo(targets[0]);
          _results.push(creep.attack(targets[0]));
        } else {
          _results.push(void 0);
        }
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };
  return this;
};
