module.exports = (creep) ->
  if creep.carry.energy < creep.carryCapacity
    sources = creep.room.find(FIND_SOURCES)
    creep.moveTo sources[0]
    creep.harvest sources[0]
  else
    creep.moveTo Game.spawns.Spawn1
    creep.transferEnergy Game.spawns.Spawn1
  return

# ---
# generated by js2coffee 2.1.0