// Generated by CoffeeScript 1.8.0
module.exports = function(creep) {
  var sources;
  if (creep.carry.energy < creep.carryCapacity) {
    sources = creep.room.find(FIND_SOURCES);
    creep.moveTo(sources[0]);
    creep.harvest(sources[0]);
  } else {
    creep.moveTo(Game.spawns.Spawn1);
    creep.transferEnergy(Game.spawns.Spawn1);
  }
};
