module.exports = (globalObj) ->
  globalObj.h = {}

  globalObj.h.spawnCreateHarvesterCreep = (spawnName, name) ->
    Game.spawns[spawnName].createHarvesterCreep name

  globalObj.h.destroyCreep = (creepName) ->
    Game.creeps[creepName].suicide()

  #aliases
  globalObj.h.schc = globalObj.h.spawnCreateHarvesterCreep
  globalObj.h.dc = globalObj.h.destroyCreep
  globalObj

# ---
# generated by js2coffee 2.1.0