// Generated by CoffeeScript 1.8.0
module.exports = function() {
  var createHarvesterCreep;
  createHarvesterCreep = function(name) {
    var newWorker, workerSuffix;
    if (typeof name === 'undefined') {
      workerSuffix = 1;
      name = 'Worker' + workerSuffix;
    }
    newWorker = this.createCreep([WORK, CARRY, MOVE], name, {
      role: 'harvester',
      group: 'default'
    });
    return newWorker;
  };
  return {
    initProrotypeHelpers: function() {
      return Spawn.prototype.createHarvesterCreep = createHarvesterCreep;
    }
  };
};
