module.exports = ->
  createHarvesterCreep = (name) ->
    if typeof name == 'undefined'
      workerSuffix = 1
      name = 'Worker' + workerSuffix
    newWorker = @createCreep([
        WORK
        CARRY
        MOVE
      ], name,
      role: 'harvester'
      group: 'default')
    newWorker

  {
  initProrotypeHelpers: ->
      Spawn::createHarvesterCreep = createHarvesterCreep
  }

# ---
# generated by js2coffee 2.1.0