module.exports = ->
  createHarvesterCreep = (name) ->
    if typeof name == 'undefined'
      nameSuffix = _.size(Memory.creeps)
      name = 'Harvester' + nameSuffix
    newWorker = @createCreep([
        WORK
        CARRY
        MOVE
      ], name,
      role: 'harvester'
      group: 'default')
    newWorker



# ---
# generated by js2coffee 2.1.0