// Generated by CoffeeScript 1.8.0
module.exports = function() {
  var createHarvesterCreep;
  return createHarvesterCreep = function(name) {
    var nameSuffix, newWorker;
    if (typeof name === 'undefined') {
      nameSuffix = _.size(Memory.creeps);
      name = 'Harvester' + nameSuffix;
    }
    newWorker = this.createCreep([WORK, CARRY, MOVE], name, {
      role: 'harvester',
      group: 'default'
    });
    return newWorker;
  };
};
