// Generated by CoffeeScript 1.8.0
var targets;
global._ = require('lodash');

global.core = require('core');

core().initExtend();

core().setup();

core().initStage();

core().initMainLoop();

core().setGlobal();
