// Generated by CoffeeScript 1.8.0
'use strict';
module.exports = function() {
  var creep, name, roles, _results;
  roles = {};
  _results = [];
  for (name in Game.creeps) {
    creep = Game.creeps[name];
    if (typeof creep.memory.role !== 'string') {
      console.log('Warning: Creep without role at ' + creep.pos.x + ',' + creep.pos.y);
      continue;
    }
    if (creep.spawning === true) {
      if (false) {
        roles[creep.memory.role].spawning(creep);
      }
      continue;
    }
    if (roles[creep.memory.role] == null) {
      roles[creep.memory.role] = require("" + creep.memory.role);
    }
    creep.beforeTurn();
    if (creep.isEnabled()) {
      _results.push(roles[creep.memory.role].turn(creep));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};
