// Generated by CoffeeScript 1.8.0
var build, findEmptyStorages, findEnergyStorages, initialize, sourcesTransferToPriority, turn;

build = function(spawn) {
  return [global.WORK, global.WORK, global.CARRY, global.MOVE];
};

initialize = function(name) {};

sourcesTransferToPriority = [global.STRUCTURE_EXTENSION, global.STRUCTURE_STORAGE, global.STRUCTURE_SPAWN];

findEnergyStorages = function() {
  var structures;
  structures = Game.spawns.Spawn1.room.find(global.FIND_MY_STRUCTURES, {
    filter: function(structure) {
      return _.indexOf(sourcesTransferToPriority, structure.structureType) !== -1;
    }
  });
  return structures;
};

findEmptyStorages = function() {
  var structures;
  structures = _.filter(findEnergyStorages(), function(structure) {
    return structure.canStoreEnergy();
  });
  return structures;
};

turn = function(creep) {
  var storages;
  creep.chooseSource();
  if (!creep.isFull()) {
    creep.setStage('harvest');
    return creep.harvestAssignedSource();
  } else {
    storages = findEmptyStorages();
    if (storages) {
      creep.setStage('transferEnergy');
      creep.moveTo(storages[0]);
      return creep.transferEnergy(storages[0]);
    }
  }
};

module.exports = {
  role: 'base_harvester',
  group: 'harvesters',
  build: build,
  initialize: initialize,
  turn: turn
};
