build = (spawn) ->
  [
    global.WORK
    global.WORK
    global.CARRY
    global.MOVE
  ]

initialize = (name) ->

sourcesTransferToPriority =
  [
    global.STRUCTURE_EXTENSION,
    global.STRUCTURE_STORAGE,
    global.STRUCTURE_SPAWN,
  ]


findEnergyStorages = ()->
  structures = Game.spawns.Spawn1.room.find(global.FIND_MY_STRUCTURES,
    filter:(structure)->
      return (_.indexOf(sourcesTransferToPriority, structure.structureType) != -1);
  )
  structures

findEmptyStorages = ()->
  structures = _.filter(findEnergyStorages(),
    (structure)->
      return structure.canStoreEnergy()
  )
  structures


turn = (creep) ->
  creep.chooseSource()
  if !creep.isFull()
    creep.setStage('harvest')
    creep.harvestAssignedSource()
  else
      storages = findEmptyStorages()
      if storages
        creep.setStage('transferEnergy')
        creep.moveTo storages[0]
        creep.transferEnergy storages[0]

module.exports =
  role: 'base_harvester',
  group:'harvesters'
  build: build
  initialize: initialize
  turn: turn

# ---
# generated by js2coffee 2.1.0