// Generated by CoffeeScript 1.8.0
var build, initialize, turn;

build = function(spawn) {
  return [global.WORK, global.WORK, global.CARRY, global.MOVE];
};

initialize = function(name) {};

turn = function(creep) {
  var targets;
  if (creep.carry.energy === 0) {
    creep.moveTo(Game.spawns.Spawn1);
    return Game.spawns.Spawn1.transferEnergy(creep);
  } else {
    targets = creep.room.find(global.FIND_CONSTRUCTION_SITES);
    if (targets.length) {
      creep.moveTo(targets[0]);
      return creep.build(targets[0]);
    }
  }
};

module.exports = {
  role: 'builder1',
  group: 'builders',
  build: build,
  initialize: initialize,
  turn: turn
};
