// Generated by CoffeeScript 1.8.0
var build, findEnergyStorages, findFullStorages, initialize, sourcesTransferToPriority, turn;

build = function(spawn) {
  return [global.CARRY, global.CARRY, global.CARRY, global.CARRY, global.MOVE, global.MOVE, global.MOVE, global.MOVE];
};

initialize = function(name) {};

sourcesTransferToPriority = [global.STRUCTURE_EXTENSION, global.STRUCTURE_STORAGE, global.STRUCTURE_SPAWN];

findEnergyStorages = function() {
  var structures;
  structures = Game.spawns.Spawn1.room.find(global.FIND_MY_STRUCTURES, {
    filter: function(structure) {
      return _.indexOf(sourcesTransferToPriority, structure.structureType) !== -1;
    }
  });
  return structures;
};

findFullStorages = function() {
  var structures;
  structures = _.filter(findEnergyStorages(), function(structure) {
    return structure.isFull();
  });
  return structures;
};

turn = function(creep) {
  var storage, storages;
  if (!creep.isFull()) {
    storages = findFullStorages();
    if (!_.isEmpty(storages)) {
      storage = storages[0];
      creep.setStage('transferEnergy');
      creep.moveTo(storage);
      return storage.transferEnergy(creep);
    }
  } else {
    if (creep.room.hasRole('cntr_worker1')) {
      creep.moveTo(creep.room.controller);
    }
    if (creep.pos.inRangeTo(creep.room.controller, 2)) {
      return creep.dropEnergy();
    }
  }
};

module.exports = {
  role: 'carrier1',
  group: 'carriers',
  build: build,
  initialize: initialize,
  turn: turn
};
