build = (spawn) ->
  [
    global.WORK
    global.WORK
    global.WORK
    global.CARRY
    global.CARRY
    global.MOVE
  ]

initialize = (name) ->

turn = (creep) ->
  if creep.isEmpty()
    energy = creep.pos.findClosest(global.FIND_DROPPED_ENERGY)
    if energy
      creep.setStage('pickup_energy')
      creep.moveTo(energy)
      creep.pickup(energy)
  else
    creep.setStage('upgradeController')
    if(creep.room.controller)
      creep.moveTo(creep.room.controller)
      creep.upgradeController(creep.room.controller)


module.exports =
  role: 'cntr_worker1'
  build: build
  initialize: initialize
  turn: turn

# ---
# generated by js2coffee 2.1.0