// Generated by CoffeeScript 1.8.0
var build, initialize, turn;

build = function(spawn) {
  return [global.WORK, global.WORK, global.WORK, global.CARRY, global.CARRY, global.MOVE];
};

initialize = function(name) {};

turn = function(creep) {
  var energy;
  if (creep.isEmpty()) {
    energy = creep.pos.findClosest(global.FIND_DROPPED_ENERGY);
    if (energy) {
      creep.setStage('pickup_energy');
      creep.moveTo(energy);
      return creep.pickup(energy);
    }
  } else {
    creep.setStage('upgradeController');
    if (creep.room.controller) {
      creep.moveTo(creep.room.controller);
      return creep.upgradeController(creep.room.controller);
    }
  }
};

module.exports = {
  role: 'cntr_worker1',
  build: build,
  initialize: initialize,
  turn: turn
};
