build = (spawn) ->
  [
    global.TOUGH
    global.MOVE
  ]

initialize = (name) ->

turn = (creep) ->

module.exports =
  role: 'spawn_logger'
  build: build
  initialize: initialize
  turn: turn

# ---
# generated by js2coffee 2.1.0