// Generated by CoffeeScript 1.8.0
var build, initialize, turn;

build = function(spawn) {
  return [global.TOUGH, global.MOVE];
};

initialize = function(name) {};

turn = function(creep) {};

module.exports = {
  role: 'spawn_logger',
  build: build,
  initialize: initialize,
  turn: turn
};
