// Generated by CoffeeScript 1.8.0
module.exports = function() {
  Game.creepsByRole = function(role) {
    return _.filter(this.creeps, function(creep) {
      return creep.memory.role === role;
    });
  };
  return Game.reinitSpawns = function() {
    return _.forEach(this.spawns, function(spawn) {
      return spawn.clearQueues();
    }, this);
  };
};
