// Generated by CoffeeScript 1.8.0
module.exports = function() {
  Source.prototype.findClosestHarvester = function(opts) {
    return this.pos.findClosest(global.FIND_MY_CREEPS, {
      filter: {
        memory: {
          role: 'harvester'
        }
      }
    });
  };
  return Source.prototype.harvesterLimit = function() {
    var areaTilesCount, terrainTiles, tiles;
    areaTilesCount = 9;
    terrainTiles = [];
    tiles = this.room.lookAtArea(this.pos.y - 1, this.pos.x - 1, this.pos.y + 1, this.pos.x + 1);
    _.forEach(tiles, function(tileRow) {
      return _.forEach(tileRow, function(tileCol) {
        var colTerrainTiles;
        colTerrainTiles = _.filter(tileCol, {
          type: 'terrain',
          terrain: 'wall'
        }, 'tile');
        return terrainTiles = terrainTiles.concat(colTerrainTiles);
      });
    });
    return areaTilesCount - _.size(terrainTiles);
  };
};
