// Generated by CoffeeScript 1.8.0
module.exports = function() {
  Structure.prototype.isFull = function() {
    return this.energy === this.energyCapacity;
  };
  return Structure.prototype.canStoreEnergy = function() {
    return !this.isFull();
  };
};
